export const coffees = [
  {
    id: "ethiopia-bensa",
    name: "Bensa Bombe",
    country: "Ethiopia",
    region: "Sidama",
    producer: "Bombe Smallholders",
    process: "Natural",
    score: 88.25,
    bags: 42,
    bagSize: 60,
    warehouse: "Hamburg",
    price: "$8.75/lb",
    priceValue: 8.75,
    status: "Spot",
    quality: "Competition",
    availability: "Available now",
    flavor: ["Blueberry", "Jasmine", "Cacao nib"],
    certification: ["Organic"],
    harvest: "2025/26",
    altitude: "1,950–2,250 masl",
    image: "/images/drying-beds.webp",
    coordinates: [38.46, 6.76],
  },
  {
    id: "colombia-el-vergel",
    name: "El Vergel Java",
    country: "Colombia",
    region: "Tolima",
    producer: "Bayter Family",
    process: "Anaerobic",
    score: 87.5,
    bags: 18,
    bagSize: 35,
    warehouse: "Rotterdam",
    price: "$9.20/lb",
    priceValue: 9.2,
    status: "Limited",
    quality: "Competition",
    availability: "Available now",
    flavor: ["Red grape", "Rose", "Brown sugar"],
    certification: ["Verified traceable"],
    harvest: "2025/26",
    altitude: "1,650 masl",
    image: "/images/red-cherries.webp",
    coordinates: [-75.23, 4.44],
  },
  {
    id: "brazil-pantano",
    name: "Pantano Yellow Bourbon",
    country: "Brazil",
    region: "Cerrado Mineiro",
    producer: "Ferrero Family",
    process: "Natural",
    score: 84.75,
    bags: 126,
    bagSize: 60,
    warehouse: "Mersin",
    price: "$5.45/lb",
    priceValue: 5.45,
    status: "Spot",
    quality: "Specialty",
    availability: "Available now",
    flavor: ["Milk chocolate", "Hazelnut", "Dried fig"],
    certification: ["Rainforest Alliance"],
    harvest: "2025/26",
    altitude: "1,150 masl",
    image: "/images/green-beans-sack.webp",
    coordinates: [-47.88, -18.91],
  },
  {
    id: "guatemala-san-patricio",
    name: "San Patricio Caturra",
    country: "Guatemala",
    region: "Huehuetenango",
    producer: "San Patricio Estate",
    process: "Washed",
    score: 86.0,
    bags: 64,
    bagSize: 69,
    warehouse: "Hamburg",
    price: "$6.85/lb",
    priceValue: 6.85,
    status: "Spot",
    quality: "Specialty",
    availability: "Available now",
    flavor: ["Red apple", "Caramel", "Citrus"],
    certification: ["Verified traceable"],
    harvest: "2025/26",
    altitude: "1,700–1,900 masl",
    image: "/images/farmer-guatemala.webp",
    coordinates: [-91.48, 15.32],
  },
  {
    id: "kenya-kirinyaga",
    name: "Kirinyaga Kii AA",
    country: "Kenya",
    region: "Kirinyaga",
    producer: "Rungeto Cooperative",
    process: "Washed",
    score: 87.75,
    bags: 24,
    bagSize: 30,
    warehouse: "Antwerp",
    price: "$8.40/lb",
    priceValue: 8.4,
    status: "Limited",
    quality: "Competition",
    availability: "Available now",
    flavor: ["Blackcurrant", "Grapefruit", "Honey"],
    certification: ["Verified traceable"],
    harvest: "2025/26",
    altitude: "1,650–1,800 masl",
    image: "/images/cherry-harvest.webp",
    coordinates: [37.3, -0.66],
  },
  {
    id: "rwanda-gitesi",
    name: "Gitesi Women’s Lot",
    country: "Rwanda",
    region: "Karongi",
    producer: "Gitesi Washing Station",
    process: "Honey",
    score: 86.5,
    bags: 31,
    bagSize: 60,
    warehouse: "Mersin",
    price: "$7.15/lb",
    priceValue: 7.15,
    status: "Spot",
    quality: "Specialty",
    availability: "Available now",
    flavor: ["Apricot", "Black tea", "Toffee"],
    certification: ["Organic", "Women produced"],
    harvest: "2025/26",
    altitude: "1,750–1,800 masl",
    image: "/images/green-cherries.webp",
    coordinates: [29.38, -2.07],
  },
  {
    id: "peru-chirinos",
    name: "Chirinos Community",
    country: "Peru",
    region: "Cajamarca",
    producer: "La Prosperidad Cooperative",
    process: "Washed",
    score: 84.5,
    bags: 88,
    bagSize: 69,
    warehouse: "Rotterdam",
    price: "$5.95/lb",
    priceValue: 5.95,
    status: "Spot",
    quality: "Specialty",
    availability: "Available now",
    flavor: ["Cocoa", "Plum", "Almond"],
    certification: ["Organic", "Fairtrade"],
    harvest: "2025/26",
    altitude: "1,650–1,950 masl",
    image: "/images/drying-beds.webp",
    coordinates: [-78.9, -5.15],
  },
  {
    id: "honduras-comicovel",
    name: "COMICOVEL Marcala",
    country: "Honduras",
    region: "La Paz",
    producer: "COMICOVEL Cooperative",
    process: "Honey",
    score: 85.25,
    bags: 0,
    bagSize: 69,
    warehouse: "In transit",
    price: "Request price",
    priceValue: 6.25,
    status: "Forward",
    quality: "Specialty",
    availability: "Arriving Sep",
    flavor: ["Praline", "Orange", "Red fruit"],
    certification: ["Organic", "Fairtrade"],
    harvest: "2025/26",
    altitude: "1,400–1,650 masl",
    image: "/images/sun-drying.webp",
    coordinates: [-87.68, 14.31],
  },
  {
    id: "indonesia-kerinci",
    name: "Kerinci Honey",
    country: "Indonesia",
    region: "Sumatra",
    producer: "Koerintji Barokah Bersama",
    process: "Honey",
    score: 85.75,
    bags: 36,
    bagSize: 60,
    warehouse: "Mersin",
    price: "$6.70/lb",
    priceValue: 6.7,
    status: "Spot",
    quality: "Specialty",
    availability: "Available now",
    flavor: ["Pineapple", "Spice", "Dark chocolate"],
    certification: ["Verified traceable"],
    harvest: "2025/26",
    altitude: "1,400–1,700 masl",
    image: "/images/coffee-farmer.webp",
    coordinates: [101.26, -1.7],
  },
];

export const origins = [
  {
    country: "Ethiopia",
    region: "Sidama · Guji · Yirgacheffe",
    coordinates: [38.46, 6.76],
    lots: 7,
    bags: 242,
    harvest: "Oct–Jan",
    profile: "Floral, stone fruit, citrus",
    image: "/images/drying-beds.webp",
  },
  {
    country: "Colombia",
    region: "Huila · Tolima · Nariño",
    coordinates: [-75.23, 4.44],
    lots: 12,
    bags: 384,
    harvest: "Year-round",
    profile: "Red fruit, caramel, tropical",
    image: "/images/coffee-farmer.webp",
  },
  {
    country: "Brazil",
    region: "Cerrado · Mantiqueira",
    coordinates: [-47.88, -18.91],
    lots: 8,
    bags: 610,
    harvest: "May–Sep",
    profile: "Chocolate, nuts, ripe fruit",
    image: "/images/sun-drying.webp",
  },
  {
    country: "Guatemala",
    region: "Huehuetenango · Antigua",
    coordinates: [-91.48, 15.32],
    lots: 5,
    bags: 198,
    harvest: "Nov–Mar",
    profile: "Citrus, cocoa, structured",
    image: "/images/farmer-guatemala.webp",
  },
  {
    country: "Kenya",
    region: "Kirinyaga · Nyeri",
    coordinates: [37.3, -0.66],
    lots: 4,
    bags: 96,
    harvest: "Oct–Dec",
    profile: "Blackcurrant, grapefruit, tea",
    image: "/images/drying-beds.webp",
  },
  {
    country: "Rwanda",
    region: "Karongi · Gakenke",
    coordinates: [29.38, -2.07],
    lots: 3,
    bags: 117,
    harvest: "Mar–Jul",
    profile: "Apricot, tea, brown sugar",
    image: "/images/coffee-farmer.webp",
  },
];

export const stories = [
  {
    title: "A new generation at San Patricio",
    location: "Huehuetenango, Guatemala",
    category: "Producer profile",
    excerpt:
      "How agronomist Diego Ovalle is pairing careful shade management with meticulous lot separation.",
    image: "/images/farmer-guatemala.webp",
    metric: "3rd generation",
  },
  {
    title: "Built by 96 women producers",
    location: "Karongi, Rwanda",
    category: "Community",
    excerpt:
      "The Gitesi women’s lot turns farm-level training and separate cherry collection into durable premiums.",
    image: "/images/coffee-farmer.webp",
    metric: "96 members",
  },
  {
    title: "Precision on the drying tables",
    location: "Sidama, Ethiopia",
    category: "Processing",
    excerpt:
      "Raised beds, slow drying, and daily moisture checks create the clarity behind Bombe’s fruit-forward cup.",
    image: "/images/drying-beds.webp",
    metric: "18–21 days",
  },
];

export const supplySteps = [
  {
    number: "01",
    title: "Producer partnerships",
    text: "Multi-harvest relationships, farm visits, and clear quality targets begin before cherry selection.",
  },
  {
    number: "02",
    title: "Selection at origin",
    text: "Our teams cup offer samples, verify lot separation, and align volumes with roaster demand.",
  },
  {
    number: "03",
    title: "Quality control",
    text: "Pre-shipment, landing, and warehouse samples are checked against the approved profile.",
  },
  {
    number: "04",
    title: "Milling & export",
    text: "Dry milling, density sorting, protective packaging, and documentation are coordinated lot by lot.",
  },
  {
    number: "05",
    title: "Warehousing",
    text: "Coffee lands in regional warehouses with current stock, sample status, and position visibility.",
  },
  {
    number: "06",
    title: "Roaster support",
    text: "Matching, sample evaluation, blend planning, and logistics support continue after the contract.",
  },
];
