// Generated by scripts/import-makendi.mjs from the Makendi V5 editable delivery.
// Lightweight index for app-shell navigation, search, and home-page previews.

export const makendiCatalogMeta = {
  "sourceName": "MAKENDI V5 Complete Editable Delivery",
  "sourceDocument": "input/MAKENDI_GC_Final.pdf",
  "generatedOn": "2026-06-20",
  "recordCount": 117,
  "originCount": 38,
  "coffeeTypes": [
    "Arabica",
    "Robusta",
    "Liberica",
    "Híbrido de Timor"
  ],
  "contact": {
    "company": "MAKENDI WORLDWIDE",
    "telephone": "+90 850 840 71 56",
    "email": "info@makendi.com",
    "website": "www.makendi.com"
  },
  "provenanceCounts": {
    "source_pdf": 823,
    "parsed_from_description": 303,
    "generated_marketing": 2033
  },
  "assetWarnings": 14
};

export const makendiOriginSummary = [
  {
    "country": "Brazil",
    "id": "brazil",
    "gradeCount": 9,
    "processes": [
      "Natural",
      "Natural / Pulped Natural",
      "Pulped Natural"
    ],
    "image": "/makendi/origins/brazil.jpg",
    "flag": "/makendi/flags/brazil.jpg",
    "heroGradeId": "mk-002-brazil-santos-ny2-cascavel-vermelha"
  },
  {
    "country": "Colombia",
    "id": "colombia",
    "gradeCount": 8,
    "processes": [
      "Fully Washed",
      "Decaffeinated / Washed",
      "Washed",
      "Honey / Anaerobic"
    ],
    "image": "/makendi/origins/colombia.jpg",
    "flag": "/makendi/flags/colombia.jpg",
    "heroGradeId": "mk-018-colombia-bochica-blend-fully-washed-screen-15-premium"
  },
  {
    "country": "Ethiopia",
    "id": "ethiopia",
    "gradeCount": 8,
    "processes": [
      "Washed / Natural",
      "Washed",
      "Natural"
    ],
    "image": "/makendi/origins/ethiopia.jpg",
    "flag": "/makendi/flags/ethiopia.jpg",
    "heroGradeId": "mk-035-ethiopia-yirgacheffe-sidamo-guji-g1-and-g2-lots"
  },
  {
    "country": "India",
    "id": "india",
    "gradeCount": 7,
    "processes": [
      "Sun-dried / Washed",
      "Washed",
      "Monsooned (Specialty)",
      "Washed (Parchment)",
      "Natural"
    ],
    "image": "/makendi/origins/india.jpg",
    "flag": "/makendi/flags/india.jpg",
    "heroGradeId": "mk-051-india-shade-grown-estate-cardamom-and-pepper-intercropped"
  },
  {
    "country": "Papua N.G.",
    "id": "papua-n-g",
    "gradeCount": 7,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/papua-n-g.jpg",
    "flag": "/makendi/flags/papua-n-g.jpg",
    "heroGradeId": "mk-085-papua-n-g-aa-grade-screen-18-7mm-premium"
  },
  {
    "country": "Indonesia",
    "id": "indonesia",
    "gradeCount": 6,
    "processes": [
      "Wet Hulled (Giling Basah)",
      "Wet Hulled / Washed",
      "Washed / Honey",
      "Washed",
      "Natural"
    ],
    "image": "/makendi/origins/indonesia.jpg",
    "flag": "/makendi/flags/indonesia.jpg",
    "heroGradeId": "mk-058-indonesia-sumatra-mandheling-grade-1-double-picked"
  },
  {
    "country": "Kenya",
    "id": "kenya",
    "gradeCount": 6,
    "processes": [
      "Washed",
      "Natural"
    ],
    "image": "/makendi/origins/kenya.jpg",
    "flag": "/makendi/flags/kenya.jpg",
    "heroGradeId": "mk-065-kenya-aa-ab-faq-main-crop-export-classifications"
  },
  {
    "country": "Vietnam",
    "id": "vietnam",
    "gradeCount": 6,
    "processes": [
      "Natural",
      "Experimental / Washed",
      "Wet Polished",
      "Washed",
      "Washed / Honey"
    ],
    "image": "/makendi/origins/vietnam.jpg",
    "flag": "/makendi/flags/vietnam.jpg",
    "heroGradeId": "mk-109-vietnam-grade-1-screen-18-clean-color-magnetically-sorted"
  },
  {
    "country": "Uganda",
    "id": "uganda",
    "gradeCount": 5,
    "processes": [
      "Washed / Natural",
      "Natural",
      "Washed"
    ],
    "image": "/makendi/origins/uganda.jpg",
    "flag": "/makendi/flags/uganda.jpg",
    "heroGradeId": "mk-104-uganda-kaweri-coffee-plantation-estate-direct-nkg-farm"
  },
  {
    "country": "Guatemala",
    "id": "guatemala",
    "gradeCount": 4,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/guatemala.jpg",
    "flag": "/makendi/flags/guatemala.jpg",
    "heroGradeId": "mk-043-guatemala-huehuetenango-antigua-micro-lot-specialty"
  },
  {
    "country": "Mexico",
    "id": "mexico",
    "gradeCount": 4,
    "processes": [
      "Washed",
      "Natural"
    ],
    "image": "/makendi/origins/mexico.jpg",
    "flag": "/makendi/flags/mexico.jpg",
    "heroGradeId": "mk-076-mexico-finca-puebla-estate-direct-nkg-corporate-farm"
  },
  {
    "country": "Burundi",
    "id": "burundi",
    "gradeCount": 3,
    "processes": [
      "Fully Washed",
      "Washed"
    ],
    "image": "/makendi/origins/burundi.jpg",
    "flag": "/makendi/flags/burundi.jpg",
    "heroGradeId": "mk-011-burundi-inyambo-blend-fully-washed-screen-15-class"
  },
  {
    "country": "Costa Rica",
    "id": "costa-rica",
    "gradeCount": 3,
    "processes": [
      "Washed",
      "Yellow / Red / Black Honey"
    ],
    "image": "/makendi/origins/costa-rica.jpg",
    "flag": "/makendi/flags/costa-rica.jpg",
    "heroGradeId": "mk-026-costa-rica-shb-tarrazu-strictly-hard-bean-1200m"
  },
  {
    "country": "Honduras",
    "id": "honduras",
    "gradeCount": 3,
    "processes": [
      "Washed",
      "Washed / Natural"
    ],
    "image": "/makendi/origins/honduras.jpg",
    "flag": "/makendi/flags/honduras.jpg",
    "heroGradeId": "mk-048-honduras-shg-ep-traceable-blends-1200m"
  },
  {
    "country": "Laos",
    "id": "laos",
    "gradeCount": 3,
    "processes": [
      "Washed",
      "Natural"
    ],
    "image": "/makendi/origins/laos.jpg",
    "flag": "/makendi/flags/laos.jpg",
    "heroGradeId": "mk-071-laos-bolavens-plateau-certified-estate-1-250-masl"
  },
  {
    "country": "Nicaragua",
    "id": "nicaragua",
    "gradeCount": 3,
    "processes": [
      "Washed",
      "Washed / Honey"
    ],
    "image": "/makendi/origins/nicaragua.jpg",
    "flag": "/makendi/flags/nicaragua.jpg",
    "heroGradeId": "mk-080-nicaragua-certified-quality-shg-regional-selects"
  },
  {
    "country": "Tanzania",
    "id": "tanzania",
    "gradeCount": 3,
    "processes": [
      "Washed",
      "Natural"
    ],
    "image": "/makendi/origins/tanzania.jpg",
    "flag": "/makendi/flags/tanzania.jpg",
    "heroGradeId": "mk-096-tanzania-kilimanjaro-mbeya-aa"
  },
  {
    "country": "Cameroon",
    "id": "cameroon",
    "gradeCount": 2,
    "processes": [
      "Natural",
      "Washed"
    ],
    "image": "/makendi/origins/cameroon.jpg",
    "flag": "/makendi/flags/cameroon.jpg",
    "heroGradeId": "mk-014-cameroon-screen-16-extra-prima"
  },
  {
    "country": "China",
    "id": "china",
    "gradeCount": 2,
    "processes": [
      "Washed",
      "Washed / Anaerobic"
    ],
    "image": "/makendi/origins/china.jpg",
    "flag": "/makendi/flags/china.jpg",
    "heroGradeId": "mk-016-china-yunnan-kongque-blend-screen-16-premium-profile-premium-pro"
  },
  {
    "country": "Ecuador",
    "id": "ecuador",
    "gradeCount": 2,
    "processes": [
      "Washed / Honey",
      "Natural"
    ],
    "image": "/makendi/origins/ecuador.jpg",
    "flag": "/makendi/flags/ecuador.jpg",
    "heroGradeId": "mk-031-ecuador-loja-high-grown"
  },
  {
    "country": "El Salvador",
    "id": "el-salvador",
    "gradeCount": 2,
    "processes": [
      "Washed / Natural",
      "Honey Processed"
    ],
    "image": "/makendi/origins/el-salvador.jpg",
    "flag": "/makendi/flags/el-salvador.jpg",
    "heroGradeId": "mk-033-el-salvador-shg-ep-bourbon-pacamara"
  },
  {
    "country": "Panama",
    "id": "panama",
    "gradeCount": 2,
    "processes": [
      "Washed / Natural / Anaerobic",
      "Washed"
    ],
    "image": "/makendi/origins/panama.jpg",
    "flag": "/makendi/flags/panama.jpg",
    "heroGradeId": "mk-083-panama-geisha-specialty-grade-boquete-valley"
  },
  {
    "country": "Philippines",
    "id": "philippines",
    "gradeCount": 2,
    "processes": [
      "Natural"
    ],
    "image": "/makendi/origins/philippines.jpg",
    "flag": "/makendi/flags/philippines.jpg",
    "heroGradeId": "mk-093-philippines-mindanao-commercial-g1"
  },
  {
    "country": "Thailand",
    "id": "thailand",
    "gradeCount": 2,
    "processes": [
      "Washed / Honey",
      "Natural"
    ],
    "image": "/makendi/origins/thailand.jpg",
    "flag": "/makendi/flags/thailand.jpg",
    "heroGradeId": "mk-099-thailand-chiang-mai-doi-chang-specialty"
  },
  {
    "country": "Timor-Leste",
    "id": "timor-leste",
    "gradeCount": 2,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/timor-leste.jpg",
    "flag": "/makendi/flags/timor-leste.jpg",
    "heroGradeId": "mk-101-timor-leste-ermera-manufahi-liquica-regional-lots"
  },
  {
    "country": "Bolivia",
    "id": "bolivia",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/bolivia.jpg",
    "flag": "/makendi/flags/bolivia.jpg",
    "heroGradeId": "mk-001-bolivia-caranavi-colonial-g1"
  },
  {
    "country": "Côte d'Ivoire",
    "id": "cote-d-ivoire",
    "gradeCount": 1,
    "processes": [
      "Natural"
    ],
    "image": "/makendi/origins/cote-d-ivoire.jpg",
    "flag": "/makendi/flags/cote-d-ivoire.jpg",
    "heroGradeId": "mk-029-cote-d-ivoire-grade-1-special-export"
  },
  {
    "country": "Dominican Rep.",
    "id": "dominican-rep",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/dominican-rep.jpg",
    "flag": "/makendi/flags/dominican-rep.jpg",
    "heroGradeId": "mk-030-dominican-rep-barahona-aaa-grand-cru"
  },
  {
    "country": "Haiti",
    "id": "haiti",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/haiti.jpg",
    "flag": "/makendi/flags/haiti.jpg",
    "heroGradeId": "mk-047-haiti-haitian-bleu-standard"
  },
  {
    "country": "Jamaica",
    "id": "jamaica",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/jamaica.jpg",
    "flag": "/makendi/flags/jamaica.jpg",
    "heroGradeId": "mk-064-jamaica-blue-mountain-wallenford-no-1"
  },
  {
    "country": "Madagascar",
    "id": "madagascar",
    "gradeCount": 1,
    "processes": [
      "Natural"
    ],
    "image": "/makendi/origins/madagascar.jpg",
    "flag": "/makendi/flags/madagascar.jpg",
    "heroGradeId": "mk-074-madagascar-elite-grade-east-coast"
  },
  {
    "country": "Malawi",
    "id": "malawi",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/malawi.jpg",
    "flag": "/makendi/flags/malawi.jpg",
    "heroGradeId": "mk-075-malawi-misuku-hills-pamwamba"
  },
  {
    "country": "Peru",
    "id": "peru",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/peru.jpg",
    "flag": "/makendi/flags/peru.jpg",
    "heroGradeId": "mk-092-peru-certified-grade-1-traceable-smallholder-cooperatives"
  },
  {
    "country": "Rwanda",
    "id": "rwanda",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/rwanda.jpg",
    "flag": "/makendi/flags/rwanda.jpg",
    "heroGradeId": "mk-095-rwanda-fully-washed-supreme-fw-bourbon"
  },
  {
    "country": "Togo",
    "id": "togo",
    "gradeCount": 1,
    "processes": [
      "Natural"
    ],
    "image": "/makendi/origins/togo.jpg",
    "flag": "/makendi/flags/togo.jpg",
    "heroGradeId": "mk-103-togo-commercial-grade-barista"
  },
  {
    "country": "Yemen",
    "id": "yemen",
    "gradeCount": 1,
    "processes": [
      "Natural"
    ],
    "image": "/makendi/origins/yemen.jpg",
    "flag": "/makendi/flags/yemen.jpg",
    "heroGradeId": "mk-115-yemen-mocha-mattari-sanani-genuine"
  },
  {
    "country": "Zambia",
    "id": "zambia",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/zambia.jpg",
    "flag": "/makendi/flags/zambia.jpg",
    "heroGradeId": "mk-116-zambia-aaa-aa-northern-province"
  },
  {
    "country": "Zimbabwe",
    "id": "zimbabwe",
    "gradeCount": 1,
    "processes": [
      "Washed"
    ],
    "image": "/makendi/origins/zimbabwe.jpg",
    "flag": "/makendi/flags/zimbabwe.jpg",
    "heroGradeId": "mk-117-zimbabwe-calveley-estate-class-1"
  }
];

export const makendiSearchIndex = [
  {
    "id": "mk-001-bolivia-caranavi-colonial-g1",
    "country": "Bolivia",
    "coffeeType": "Arabica",
    "shortGrade": "Caranavi Colonial G1",
    "processDisplay": "Washed",
    "image": "/makendi/origins/bolivia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Bolivia Arabica Caranavi Colonial G1 Specialty Grade, Screen 16+ | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 1
  },
  {
    "id": "mk-002-brazil-santos-ny2-cascavel-vermelha",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Santos NY2 - (Cascavel Vermelha)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Santos NY2 - (Cascavel Vermelha) NY 2/3 Grade | ≤3 defects/300g | Flavor: Red Fruit Natural Red Fruit NY 2/3 Grade Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 2
  },
  {
    "id": "mk-003-brazil-santos-ny2-cascavel-verde",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Santos NY2 - (Cascavel Verde)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Citrus",
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts"
    ],
    "searchText": "Brazil Arabica Santos NY2 - (Cascavel Verde) NY 2/3 Grade | ≤3 defects/300g | Flavor: Citrus Natural Citrus NY 2/3 Grade Citrus Red Fruit Chocolate Roasted Nuts Espresso Filter Coffee French Press Blends",
    "sourceNumber": 3
  },
  {
    "id": "mk-004-brazil-fazenda-da-lagoa-estate-direct-nkg-corporate-farm",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Fazenda da Lagoa Estate (Direct NKG Corporate Farm)",
    "processDisplay": "Natural / Pulped Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Fazenda da Lagoa Estate (Direct NKG Corporate Farm) COB: Estritamente Mole (Strictly Soft), Screen 15-17 Natural / Pulped Natural Red Fruit, Chocolate, Roasted Nuts COB: Estritamente Mole (Strictly Soft) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 4
  },
  {
    "id": "mk-005-brazil-sul-de-minas-and-cerrado-mineiro-regional-blends",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Sul de Minas & Cerrado Mineiro Regional Blends",
    "processDisplay": "Natural / Pulped Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Sul de Minas & Cerrado Mineiro Regional Blends COB: Mole (Soft) to Estritamente Mole, Screen 15-17 Natural / Pulped Natural Red Fruit, Chocolate, Roasted Nuts COB: Mole (Soft) to Estritamente Mole Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 5
  },
  {
    "id": "mk-006-brazil-santos-ny-2-3-strictly-soft-fine-cup-screen-17-18",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Santos NY 2/3 Strictly Soft Fine Cup (Screen 17/18)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Santos NY 2/3 Strictly Soft Fine Cup (Screen 17/18) COB: Estritamente Mole, Chato Graúdo | ≤3 defects/300g Natural / Dry Processed Red Fruit, Chocolate, Roasted Nuts COB: Estritamente Mole Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 6
  },
  {
    "id": "mk-007-brazil-sul-de-minas-fine-cup-screen-15-16",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Sul de Minas Fine Cup (Screen 15/16)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Sul de Minas Fine Cup (Screen 15/16) COB: Mole (Soft), Chato Médio | ≤5 defects/300g Natural / Dry Processed Red Fruit, Chocolate, Roasted Nuts COB: Mole (Soft) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 7
  },
  {
    "id": "mk-008-brazil-cerrado-mineiro-pulped-natural-semi-washed",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Cerrado Mineiro Pulped Natural (Semi-washed)",
    "processDisplay": "Pulped Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Cerrado Mineiro Pulped Natural (Semi-washed) COB: Estritamente Mole, Screen 15-17 Pulped Natural Red Fruit, Chocolate, Roasted Nuts COB: Estritamente Mole Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 8
  },
  {
    "id": "mk-009-brazil-mogiana-ny-2-3-good-cup",
    "country": "Brazil",
    "coffeeType": "Arabica",
    "shortGrade": "Mogiana NY 2/3 Good Cup",
    "processDisplay": "Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Brazil Arabica Mogiana NY 2/3 Good Cup COB: Apenas Mole (Fairly Soft), Screen 15-17 Natural / Dry Processed Red Fruit, Chocolate, Roasted Nuts COB: Apenas Mole (Fairly Soft) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 9
  },
  {
    "id": "mk-010-brazil-conilon-espirito-santo-screen-16-extra-conilon",
    "country": "Brazil",
    "coffeeType": "Robusta",
    "shortGrade": "Conilon - Espírito Santo Screen 16 Extra - (Conilon)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/brazil.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Brazil Robusta Conilon - Espírito Santo Screen 16 Extra - (Conilon) Chato Médio (SNI-Robusta Q1) | ≤11 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Chato Médio (SNI-Robusta Q1) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 10
  },
  {
    "id": "mk-011-burundi-inyambo-blend-fully-washed-screen-15-class",
    "country": "Burundi",
    "coffeeType": "Arabica",
    "shortGrade": "Inyambo Blend (Fully Washed Screen 15+ class)",
    "processDisplay": "Fully Washed",
    "image": "/makendi/origins/burundi.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Burundi Arabica Inyambo Blend (Fully Washed Screen 15+ class) Specialty Grade, Screen 15+ | ≤8 defects/300g Fully Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 11
  },
  {
    "id": "mk-012-burundi-turaco-blend-fully-washed-screen-15-rainforest-alliance",
    "country": "Burundi",
    "coffeeType": "Arabica",
    "shortGrade": "Turaco Blend (Fully Washed Screen 15+ / Rainforest Alliance)",
    "processDisplay": "Fully Washed",
    "image": "/makendi/origins/burundi.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Burundi Arabica Turaco Blend (Fully Washed Screen 15+ / Rainforest Alliance) Specialty Grade, Screen 15+, RFA Certified Fully Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 12
  },
  {
    "id": "mk-013-burundi-fully-washed-a-super-fine-kayanza",
    "country": "Burundi",
    "coffeeType": "Arabica",
    "shortGrade": "Fully Washed A / Super Fine Kayanza",
    "processDisplay": "Washed",
    "image": "/makendi/origins/burundi.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Burundi Arabica Fully Washed A / Super Fine Kayanza Premium Grade, Screen 15+ | ≤8 defects/300g Washed Citrus, Floral, Cocoa Premium Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 13
  },
  {
    "id": "mk-014-cameroon-screen-16-extra-prima",
    "country": "Cameroon",
    "coffeeType": "Robusta",
    "shortGrade": "Screen 16+ Extra Prima",
    "processDisplay": "Natural",
    "image": "/makendi/origins/cameroon.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Cameroon Robusta Screen 16+ Extra Prima Chato Médio grade (Commercial Prime) | ≤21 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Chato Médio grade (Commercial Prime) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 14
  },
  {
    "id": "mk-015-cameroon-western-highlands-g1",
    "country": "Cameroon",
    "coffeeType": "Arabica",
    "shortGrade": "Western Highlands G1",
    "processDisplay": "Washed",
    "image": "/makendi/origins/cameroon.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Cameroon Arabica Western Highlands G1 Specialty Grade 1 | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty Grade 1 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 15
  },
  {
    "id": "mk-016-china-yunnan-kongque-blend-screen-16-premium-profile-premium-pro",
    "country": "China",
    "coffeeType": "Arabica",
    "shortGrade": "Yunnan KongQue Blend (Screen 16+ Premium Profile) - (Premium Profile)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/china.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "China Arabica Yunnan KongQue Blend (Screen 16+ Premium Profile) - (Premium Profile) Screen 16+ (6.35mm) | ≤8 defects/300g Washed Citrus, Floral, Cocoa Screen 16+ (6.35mm) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 16
  },
  {
    "id": "mk-017-china-yunnan-grade-1-catimor-pu-er-region",
    "country": "China",
    "coffeeType": "Arabica",
    "shortGrade": "Yunnan Grade 1 - (Catimor, Pu'er Region)",
    "processDisplay": "Washed / Anaerobic",
    "image": "/makendi/origins/china.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "China Arabica Yunnan Grade 1 - (Catimor, Pu'er Region) Specialty G1, Screen 15+ | ≤5 defects/300g Washed / Double Anaerobic Tropical Fruit, Red Fruit, Caramel Specialty G1 Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 17
  },
  {
    "id": "mk-018-colombia-bochica-blend-fully-washed-screen-15-premium",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Bochica Blend (Fully Washed Screen 15+ Premium)",
    "processDisplay": "Fully Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Colombia Arabica Bochica Blend (Fully Washed Screen 15+ Premium) FNC: Extra Grade (Screen 16) | ≤10 imperfections Fully Washed Citrus, Floral, Cocoa FNC: Extra Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 18
  },
  {
    "id": "mk-019-colombia-huitaca-blend-fully-washed-screen-15-premium",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Huitaca Blend (Fully Washed Screen 15+ Premium)",
    "processDisplay": "Fully Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Colombia Arabica Huitaca Blend (Fully Washed Screen 15+ Premium) FNC: Extra Grade (Screen 16) | ≤10 imperfections Fully Washed Citrus, Floral, Cocoa FNC: Extra Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 19
  },
  {
    "id": "mk-020-colombia-tumbaga-ep-proprietary-sugarcane-process-decaf",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Tumbaga EP (Proprietary Sugarcane Process Decaf)",
    "processDisplay": "Decaffeinated / Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Cocoa",
      "Caramel",
      "Roasted Nuts",
      "Smooth Finish"
    ],
    "searchText": "Colombia Arabica Tumbaga EP (Proprietary Sugarcane Process Decaf) FNC: Excelso EP (Screen 14-16), European Prep | ≤10 imperfections Decaffeinated / Washed Cocoa, Caramel, Roasted Nuts FNC: Excelso EP Cocoa Caramel Roasted Nuts Smooth Finish Decaf Espresso Filter Coffee Milk Drinks Blends",
    "sourceNumber": 20
  },
  {
    "id": "mk-021-colombia-medellin-tolima-huila-regional-selected-lots",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Medellín / Tolima / Huila Regional Selected Lots",
    "processDisplay": "Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Colombia Arabica Medellín / Tolima / Huila Regional Selected Lots FNC: Excelso (Screen 14-16), moisture ≤12% Washed Citrus, Floral, Cocoa FNC: Excelso Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 21
  },
  {
    "id": "mk-022-colombia-supremo-ep-screen-17-18-european-prep",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Supremo EP (Screen 17/18, European Prep)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Colombia Arabica Supremo EP (Screen 17/18, European Prep) FNC: Supremo (Screen 17, 6.70mm) | ≤10 imperfections Washed Citrus, Floral, Cocoa FNC: Supremo (Screen 17 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 22
  },
  {
    "id": "mk-023-colombia-excelso-ep-screen-15-16-standard-export",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Excelso EP (Screen 15/16, Standard Export)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Colombia Arabica Excelso EP (Screen 15/16, Standard Export) FNC: Extra Grade (Screen 16, 6.35mm) Washed Citrus, Floral, Cocoa FNC: Extra Grade (Screen 16 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 23
  },
  {
    "id": "mk-024-colombia-huila-regional-specialty-high-acidity-lot",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Huila Regional Specialty (High acidity lot)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "High Acidity",
      "Citrus",
      "Floral",
      "Cocoa"
    ],
    "searchText": "Colombia Arabica Huila Regional Specialty (High acidity lot) FNC: Excelso (Screen 14-16), Huila D.O. | Flavor: High Acidity Washed High Acidity FNC: Excelso High Acidity Citrus Floral Cocoa Filter Coffee Espresso French Press Blends",
    "sourceNumber": 24
  },
  {
    "id": "mk-025-colombia-pink-bourbon-caturra-micro-lot",
    "country": "Colombia",
    "coffeeType": "Arabica",
    "shortGrade": "Pink Bourbon / Caturra Micro-lot",
    "processDisplay": "Honey / Anaerobic",
    "image": "/makendi/origins/colombia.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Colombia Arabica Pink Bourbon / Caturra Micro-lot Specialty Grade 1, Screen 15+ | ≤5 defects/300g Honey / Anaerobic Fermentation Tropical Fruit, Red Fruit, Caramel Specialty Grade 1 Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 25
  },
  {
    "id": "mk-026-costa-rica-shb-tarrazu-strictly-hard-bean-1200m",
    "country": "Costa Rica",
    "coffeeType": "Arabica",
    "shortGrade": "SHB Tarrazu (Strictly Hard Bean, >1200m)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/costa-rica.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Costa Rica Arabica SHB Tarrazu (Strictly Hard Bean, >1200m) INTECO: SHB (>1200m), Screen 15+ | ≤13 defects/300g Washed Citrus, Floral, Cocoa INTECO: SHB (>1200m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 26
  },
  {
    "id": "mk-027-costa-rica-central-valley-specialty-honey",
    "country": "Costa Rica",
    "coffeeType": "Arabica",
    "shortGrade": "Central Valley Specialty Honey",
    "processDisplay": "Yellow / Red / Black Honey",
    "image": "/makendi/origins/costa-rica.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Costa Rica Arabica Central Valley Specialty Honey SHB grade, Screen 15+, ICAFE certified Yellow / Red / Black Honey Tropical Fruit, Red Fruit, Caramel SHB grade Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 27
  },
  {
    "id": "mk-028-costa-rica-tres-rios-shb-ep",
    "country": "Costa Rica",
    "coffeeType": "Arabica",
    "shortGrade": "Tres Ríos SHB EP",
    "processDisplay": "Washed",
    "image": "/makendi/origins/costa-rica.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Costa Rica Arabica Tres Ríos SHB EP SHB (>1200m), European Prep, Screen 16+ Washed Citrus, Floral, Cocoa SHB (>1200m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 28
  },
  {
    "id": "mk-029-cote-d-ivoire-grade-1-special-export",
    "country": "Côte d'Ivoire",
    "coffeeType": "Robusta",
    "shortGrade": "Grade 1 / Spécial Export",
    "processDisplay": "Natural",
    "image": "/makendi/origins/cote-d-ivoire.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Côte d'Ivoire Robusta Grade 1 / Spécial Export (Robusta ICO standard), Screen 16+ | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice (Robusta ICO standard) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 29
  },
  {
    "id": "mk-030-dominican-rep-barahona-aaa-grand-cru",
    "country": "Dominican Rep.",
    "coffeeType": "Arabica",
    "shortGrade": "Barahona AAA Grand Cru",
    "processDisplay": "Washed",
    "image": "/makendi/origins/dominican-rep.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Dominican Rep. Arabica Barahona AAA Grand Cru Screen 18+ (7.14mm), Grand Cru | ≤5 defects/300g Washed Citrus, Floral, Cocoa Screen 18+ (7.14mm) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 30
  },
  {
    "id": "mk-031-ecuador-loja-high-grown",
    "country": "Ecuador",
    "coffeeType": "Arabica",
    "shortGrade": "Loja High Grown",
    "processDisplay": "Washed / Honey",
    "image": "/makendi/origins/ecuador.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Ecuador Arabica Loja High Grown Screen 15+ (6.00mm) (Exchange Grade) | ≤23 defects/300g Washed / Honey Tropical Fruit, Red Fruit, Caramel Screen 15+ (6.00mm) (Exchange Grade) Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 31
  },
  {
    "id": "mk-032-ecuador-napo-sucumbios-commercial",
    "country": "Ecuador",
    "coffeeType": "Robusta",
    "shortGrade": "Napo/Sucumbíos Commercial",
    "processDisplay": "Natural",
    "image": "/makendi/origins/ecuador.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Ecuador Robusta Napo/Sucumbíos Commercial Commercial grade | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Commercial grade Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 32
  },
  {
    "id": "mk-033-el-salvador-shg-ep-bourbon-pacamara",
    "country": "El Salvador",
    "coffeeType": "Arabica",
    "shortGrade": "SHG EP Bourbon / Pacamara",
    "processDisplay": "Washed / Natural",
    "image": "/makendi/origins/el-salvador.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "El Salvador Arabica SHG EP Bourbon / Pacamara SHG (>1200m), European Prep, Screen 15+ Washed / Natural Red Fruit, Chocolate, Roasted Nuts SHG (>1200m) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 33
  },
  {
    "id": "mk-034-el-salvador-santa-ana-high-mountain-honey",
    "country": "El Salvador",
    "coffeeType": "Arabica",
    "shortGrade": "Santa Ana High Mountain Honey",
    "processDisplay": "Honey Processed",
    "image": "/makendi/origins/el-salvador.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "El Salvador Arabica Santa Ana High Mountain Honey SHG (>1200m), Screen 15+ | ≤13 defects Honey Processed Tropical Fruit, Red Fruit, Caramel SHG (>1200m) Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 34
  },
  {
    "id": "mk-035-ethiopia-yirgacheffe-sidamo-guji-g1-and-g2-lots",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Yirgacheffe / Sidamo / Guji G1 & G2 Lots",
    "processDisplay": "Washed / Natural",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Ethiopia Arabica Yirgacheffe / Sidamo / Guji G1 & G2 Lots Specialty G1, Screen 14-16 | ≤5 defects/300g Washed / Natural Red Fruit, Chocolate, Roasted Nuts Specialty G1 Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 35
  },
  {
    "id": "mk-036-ethiopia-yirgacheffe-grade-1-specialty-micro-lot",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Yirgacheffe Grade 1 (Specialty micro-lot)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Ethiopia Arabica Yirgacheffe Grade 1 (Specialty micro-lot) Specialty G1, density 710-780 g/L | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty G1 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 36
  },
  {
    "id": "mk-037-ethiopia-guji-grade-1-high-density-high-floral",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Guji Grade 1 (High density, high floral)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Floral",
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts"
    ],
    "searchText": "Ethiopia Arabica Guji Grade 1 (High density, high floral) Specialty G1, density 710-780 g/L | ≤5 defects/300g | Flavor: Floral Natural / Unwashed Floral Specialty G1 Floral Red Fruit Chocolate Roasted Nuts Espresso Filter Coffee French Press Blends",
    "sourceNumber": 37
  },
  {
    "id": "mk-038-ethiopia-sidamo-grade-2-standard-export-class",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Sidamo Grade 2 (Standard export class)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Ethiopia Arabica Sidamo Grade 2 (Standard export class) Specialty G2 (5-8 defects/300g), Screen 14+ | 5-8 defects/300g Washed Citrus, Floral, Cocoa Specialty G2 (5-8 defects/300g) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 38
  },
  {
    "id": "mk-039-ethiopia-sidamo-grade-3-4-commercial-natural",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Sidamo Grade 3/4 (Commercial natural)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Ethiopia Arabica Sidamo Grade 3/4 (Commercial natural) Commercial Grade (9-86 defects/300g) | 9-86 defects/300g Natural / Unwashed Red Fruit, Chocolate, Roasted Nuts Commercial Grade (9-86 defects/300g) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 39
  },
  {
    "id": "mk-040-ethiopia-harrar-longberry-g4-wild-complex-berry",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Harrar Longberry G4 (Wild, complex berry)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Wild",
      "Complex Berry",
      "Red Fruit",
      "Chocolate"
    ],
    "searchText": "Ethiopia Arabica Harrar Longberry G4 (Wild, complex berry) Commercial G4 (24-86 defects/300g), Longberry varietal | 24-86 defects/300g | Flavor: Wild, Complex Berry Natural / Unwashed Wild, Complex Berry Commercial G4 (24-86 defects/300g) Wild Complex Berry Red Fruit Chocolate Espresso Filter Coffee French Press Blends",
    "sourceNumber": 40
  },
  {
    "id": "mk-041-ethiopia-djimmah-g5-commercial-grading-block",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Djimmah G5 (Commercial grading block)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Ethiopia Arabica Djimmah G5 (Commercial grading block) Off Grade G5 (>86 defects/300g) Natural / Unwashed Red Fruit, Chocolate, Roasted Nuts Off Grade G5 (>86 defects/300g) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 41
  },
  {
    "id": "mk-042-ethiopia-limu-grade-2",
    "country": "Ethiopia",
    "coffeeType": "Arabica",
    "shortGrade": "Limu Grade 2",
    "processDisplay": "Washed",
    "image": "/makendi/origins/ethiopia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Ethiopia Arabica Limu Grade 2 Specialty G2 (5-8 defects/300g), Screen 14+ | 5-8 defects/300g Washed Citrus, Floral, Cocoa Specialty G2 (5-8 defects/300g) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 42
  },
  {
    "id": "mk-043-guatemala-huehuetenango-antigua-micro-lot-specialty",
    "country": "Guatemala",
    "coffeeType": "Arabica",
    "shortGrade": "Huehuetenango / Antigua Micro-lot Specialty",
    "processDisplay": "Washed",
    "image": "/makendi/origins/guatemala.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Guatemala Arabica Huehuetenango / Antigua Micro-lot Specialty SHB (>1350m), Screen 15+ | ≤5 defects/300g Washed Citrus, Floral, Cocoa SHB (>1350m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 43
  },
  {
    "id": "mk-044-guatemala-shb-huehuetenango-highland",
    "country": "Guatemala",
    "coffeeType": "Arabica",
    "shortGrade": "SHB Huehuetenango Highland",
    "processDisplay": "Washed",
    "image": "/makendi/origins/guatemala.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Guatemala Arabica SHB Huehuetenango Highland SHB (>1350m), density 700+ g/L Washed Citrus, Floral, Cocoa SHB (>1350m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 44
  },
  {
    "id": "mk-045-guatemala-shb-antigua-genuine-volcanic-soil-class",
    "country": "Guatemala",
    "coffeeType": "Arabica",
    "shortGrade": "SHB Antigua Genuine (Volcanic soil class)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/guatemala.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Guatemala Arabica SHB Antigua Genuine (Volcanic soil class) SHB (>1350m), Antigua D.O., volcanic soil Washed Citrus, Floral, Cocoa SHB (>1350m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 45
  },
  {
    "id": "mk-046-guatemala-prime-washed-lowland-commercial",
    "country": "Guatemala",
    "coffeeType": "Arabica",
    "shortGrade": "Prime Washed (Lowland commercial)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/guatemala.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Guatemala Arabica Prime Washed (Lowland commercial) Prime grade (<1200m), Screen 13-14 Washed Citrus, Floral, Cocoa Prime grade (<1200m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 46
  },
  {
    "id": "mk-047-haiti-haitian-bleu-standard",
    "country": "Haiti",
    "coffeeType": "Arabica",
    "shortGrade": "Haitian Bleu Standard",
    "processDisplay": "Washed",
    "image": "/makendi/origins/haiti.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Haiti Arabica Haitian Bleu Standard SCA Specialty Grade, Screen 15+ | ≤5 defects/300g Washed Citrus, Floral, Cocoa SCA Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 47
  },
  {
    "id": "mk-048-honduras-shg-ep-traceable-blends-1200m",
    "country": "Honduras",
    "coffeeType": "Arabica",
    "shortGrade": "SHG EP Traceable Blends (>1200m)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/honduras.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Honduras Arabica SHG EP Traceable Blends (>1200m) SHG (>1350m), European Prep, Screen 15+ Washed Citrus, Floral, Cocoa SHG (>1350m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 48
  },
  {
    "id": "mk-049-honduras-hg-high-grown-standard-export",
    "country": "Honduras",
    "coffeeType": "Arabica",
    "shortGrade": "HG - (High Grown, Standard export)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/honduras.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Honduras Arabica HG - (High Grown, Standard export) HG (1200-1350m), Screen 14+ Washed Citrus, Floral, Cocoa HG (1200-1350m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 49
  },
  {
    "id": "mk-050-honduras-copan-regional-specialty",
    "country": "Honduras",
    "coffeeType": "Arabica",
    "shortGrade": "Copan Regional Specialty",
    "processDisplay": "Washed / Natural",
    "image": "/makendi/origins/honduras.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Honduras Arabica Copan Regional Specialty SHB grade, Screen 15+ | ≤8 defects/300g Washed / Natural Red Fruit, Chocolate, Roasted Nuts SHB grade Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 50
  },
  {
    "id": "mk-051-india-shade-grown-estate-cardamom-and-pepper-intercropped",
    "country": "India",
    "coffeeType": "Arabica",
    "shortGrade": "Shade-Grown Estate (Cardamom & Pepper Intercropped)",
    "processDisplay": "Sun-dried / Washed",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "India Arabica Shade-Grown Estate (Cardamom & Pepper Intercropped) Plantation Grade, Screen 15+ | ≤13 defects Fully Sundried / Washed Citrus, Floral, Cocoa Plantation Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 51
  },
  {
    "id": "mk-052-india-plantation-aaa-screen-19-premium",
    "country": "India",
    "coffeeType": "Arabica",
    "shortGrade": "Plantation AAA (Screen 19, Premium)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "India Arabica Plantation AAA (Screen 19, Premium) PL AAA: Screen 19+ (6.65mm+ on S17) | ≤5 defects Washed Citrus, Floral, Cocoa PL AAA: Screen 19+ (6.65mm+ on S17) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 52
  },
  {
    "id": "mk-053-india-monsooned-malabar-aa-exposed-to-monsoon-winds",
    "country": "India",
    "coffeeType": "Arabica",
    "shortGrade": "Monsooned Malabar AA (Exposed to monsoon winds)",
    "processDisplay": "Monsooned (Specialty)",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Cocoa",
      "Caramel",
      "Roasted Nuts",
      "Balanced Finish"
    ],
    "searchText": "India Arabica Monsooned Malabar AA (Exposed to monsoon winds) Cherry AA grade, exception: moisture >12.5% permitted Monsooned (Specialty) Cocoa, Caramel, Roasted Nuts Cherry AA grade Cocoa Caramel Roasted Nuts Balanced Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 53
  },
  {
    "id": "mk-054-india-mysore-nugget-extra-bold-aaa-screen-19",
    "country": "India",
    "coffeeType": "Arabica",
    "shortGrade": "Mysore Nugget Extra Bold - (AAA, Screen 19+)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "India Arabica Mysore Nugget Extra Bold - (AAA, Screen 19+) PL AAA / AC AAA, Screen 19+ (7.50mm+) | ≤5 defects Washed Citrus, Floral, Cocoa PL AAA / AC AAA Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 54
  },
  {
    "id": "mk-055-india-parchment-ab-screen-15-16",
    "country": "India",
    "coffeeType": "Robusta",
    "shortGrade": "Parchment AB (Screen 15/16)",
    "processDisplay": "Washed (Parchment)",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "India Robusta Parchment AB (Screen 15/16) Parchment AB: Screen 15/16 (6.00-6.35mm) | ≤25 defects Washed (Parchment) Dark Cocoa, Roasted Nuts, Spice Parchment AB: Screen 15/16 (6.00-6.35mm) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 55
  },
  {
    "id": "mk-056-india-kaapi-royale-screen-18-no-defects",
    "country": "India",
    "coffeeType": "Robusta",
    "shortGrade": "Kaapi Royale (Screen 18, No defects)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "India Robusta Kaapi Royale (Screen 18, No defects) Premium washed Robusta, Screen 18 (7.14mm) | ≤5 defects Washed Dark Cocoa, Roasted Nuts, Spice Premium washed Robusta Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 56
  },
  {
    "id": "mk-057-india-cherry-aaa-screen-19-unwashed",
    "country": "India",
    "coffeeType": "Robusta",
    "shortGrade": "Cherry AAA (Screen 19, Unwashed)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/india.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "India Robusta Cherry AAA (Screen 19, Unwashed) Cherry AAA: Screen 19+ (7.50mm+) | ≤11 defects Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Cherry AAA: Screen 19+ (7.50mm+) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 57
  },
  {
    "id": "mk-058-indonesia-sumatra-mandheling-grade-1-double-picked",
    "country": "Indonesia",
    "coffeeType": "Arabica",
    "shortGrade": "Sumatra Mandheling Grade 1 Double Picked",
    "processDisplay": "Wet Hulled (Giling Basah)",
    "image": "/makendi/origins/indonesia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Indonesia Arabica Sumatra Mandheling Grade 1 Double Picked SNI Q1: Giling Basah, Screen 14-16 | ≤11 defects/300g Wet Hulled (Giling Basah) Citrus, Floral, Cocoa SNI Q1: Giling Basah Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 58
  },
  {
    "id": "mk-059-indonesia-sumatra-gayo-mountain-grade-1-organic",
    "country": "Indonesia",
    "coffeeType": "Arabica",
    "shortGrade": "Sumatra Gayo Mountain Grade 1 Organic",
    "processDisplay": "Wet Hulled (Giling Basah)",
    "image": "/makendi/origins/indonesia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Indonesia Arabica Sumatra Gayo Mountain Grade 1 Organic SNI Q1: Organic certified, Screen 14+ | ≤11 defects/300g Wet Hulled (Giling Basah) Citrus, Floral, Cocoa SNI Q1: Organic certified Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 59
  },
  {
    "id": "mk-060-indonesia-sulawesi-toraja-g1-premium",
    "country": "Indonesia",
    "coffeeType": "Arabica",
    "shortGrade": "Sulawesi Toraja G1 (Premium)",
    "processDisplay": "Wet Hulled / Washed",
    "image": "/makendi/origins/indonesia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Indonesia Arabica Sulawesi Toraja G1 (Premium) SNI Q1: Screen 15+ | ≤11 defects/300g Wet Hulled / Washed Citrus, Floral, Cocoa SNI Q1: Screen 15+ Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 60
  },
  {
    "id": "mk-061-indonesia-bali-kintamani-single-origin-specialty",
    "country": "Indonesia",
    "coffeeType": "Arabica",
    "shortGrade": "Bali Kintamani (Single-Origin Specialty)",
    "processDisplay": "Washed / Honey",
    "image": "/makendi/origins/indonesia.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Indonesia Arabica Bali Kintamani (Single-Origin Specialty) SNI Q1, Single-origin, Screen 15+ Washed / Honey Tropical Fruit, Red Fruit, Caramel SNI Q1 Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 61
  },
  {
    "id": "mk-062-indonesia-java-preanger-government-estate",
    "country": "Indonesia",
    "coffeeType": "Arabica",
    "shortGrade": "Java Preanger - (Government Estate)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/indonesia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Indonesia Arabica Java Preanger - (Government Estate) SNI Q1: Government Estate | ≤11 defects/300g Washed Citrus, Floral, Cocoa SNI Q1: Government Estate Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 62
  },
  {
    "id": "mk-063-indonesia-java-east-grade-1-large-screen",
    "country": "Indonesia",
    "coffeeType": "Robusta",
    "shortGrade": "Java East Grade 1 (Large Screen)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/indonesia.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Indonesia Robusta Java East Grade 1 (Large Screen) SNI Q1: Screen 16+ | ≤25 defects/300g Unwashed / Natural Dark Cocoa, Roasted Nuts, Spice SNI Q1: Screen 16+ Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 63
  },
  {
    "id": "mk-064-jamaica-blue-mountain-wallenford-no-1",
    "country": "Jamaica",
    "coffeeType": "Arabica",
    "shortGrade": "Blue Mountain Wallenford No. 1",
    "processDisplay": "Washed",
    "image": "/makendi/origins/jamaica.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Jamaica Arabica Blue Mountain Wallenford No. 1 Jamaica Grade 1: Screen 17+ (6.70mm+) | ≤5 defects/300g Washed Citrus, Floral, Cocoa Jamaica Grade 1: Screen 17+ (6.70mm+) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 64
  },
  {
    "id": "mk-065-kenya-aa-ab-faq-main-crop-export-classifications",
    "country": "Kenya",
    "coffeeType": "Arabica",
    "shortGrade": "AA / AB FAQ Main Crop Export Classifications",
    "processDisplay": "Washed",
    "image": "/makendi/origins/kenya.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Kenya Arabica AA / AB FAQ Main Crop Export Classifications AA: Screen 17/18 (7.14mm+), AB: Screen 15/16 (6.35mm+) Washed Citrus, Floral, Cocoa AA: Screen 17/18 (7.14mm+) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 65
  },
  {
    "id": "mk-066-kenya-aa-faq-top-screen-17-18-7-14mm",
    "country": "Kenya",
    "coffeeType": "Arabica",
    "shortGrade": "AA FAQ / TOP (Screen 17/18, 7.14mm)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/kenya.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Kenya Arabica AA FAQ / TOP (Screen 17/18, 7.14mm) Screen 17/18, density 700+ g/L | ≤8 defects/300g Washed Citrus, Floral, Cocoa Screen 17/18 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 66
  },
  {
    "id": "mk-067-kenya-ab-faq-top-screen-15-16-6-35mm",
    "country": "Kenya",
    "coffeeType": "Arabica",
    "shortGrade": "AB FAQ / TOP (Screen 15/16, 6.35mm)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/kenya.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Kenya Arabica AB FAQ / TOP (Screen 15/16, 6.35mm) Screen 15/16, ~40% of Kenya export volume Washed Citrus, Floral, Cocoa Screen 15/16 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 67
  },
  {
    "id": "mk-068-kenya-pb-peaberry-round-mutated-sorting",
    "country": "Kenya",
    "coffeeType": "Arabica",
    "shortGrade": "PB (Peaberry, round mutated sorting)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/kenya.jpg",
    "tastingNotes": [
      "Berry",
      "Citrus",
      "Floral",
      "Cocoa"
    ],
    "searchText": "Kenya Arabica PB (Peaberry, round mutated sorting) Screen 12+ (~5% of crop), single round bean, high density | Flavor: Berry Washed Berry Screen 12+ (~5% of crop) Berry Citrus Floral Cocoa Filter Coffee Espresso French Press Blends",
    "sourceNumber": 68
  },
  {
    "id": "mk-069-kenya-e-elephant-bean-massive-size-fusion",
    "country": "Kenya",
    "coffeeType": "Arabica",
    "shortGrade": "E - (Elephant Bean, massive size fusion)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/kenya.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Kenya Arabica E - (Elephant Bean, massive size fusion) Screen 20+ (8.00mm+, rare oversized fused beans) Washed Citrus, Floral, Cocoa Screen 20+ (8.00mm+ Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 69
  },
  {
    "id": "mk-070-kenya-mbuni-heavy-mh-dry-milled-pods",
    "country": "Kenya",
    "coffeeType": "Arabica",
    "shortGrade": "Mbuni Heavy (MH, dry-milled pods)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/kenya.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Kenya Arabica Mbuni Heavy (MH, dry-milled pods) MH: Natural dried (Mbuni), lower grade commercial Unwashed / Dry Processed Red Fruit, Chocolate, Roasted Nuts MH: Natural dried (Mbuni) Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 70
  },
  {
    "id": "mk-071-laos-bolavens-plateau-certified-estate-1-250-masl",
    "country": "Laos",
    "coffeeType": "Arabica",
    "shortGrade": "Bolavens Plateau Certified Estate (1,250 MASL)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/laos.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Laos Arabica Bolavens Plateau Certified Estate (1,250 MASL) Screen 15+, 1250 MASL | ≤8 defects/300g Washed Citrus, Floral, Cocoa Screen 15+ Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 71
  },
  {
    "id": "mk-072-laos-bolaven-plateau-g1",
    "country": "Laos",
    "coffeeType": "Robusta",
    "shortGrade": "Bolaven Plateau G1",
    "processDisplay": "Natural",
    "image": "/makendi/origins/laos.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Laos Robusta Bolaven Plateau G1 G1: (Robusta ICO standard), Screen 16+ | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice G1: (Robusta ICO standard) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 72
  },
  {
    "id": "mk-073-laos-champasak-typica-catimor",
    "country": "Laos",
    "coffeeType": "Arabica",
    "shortGrade": "Champasak Typica / Catimor",
    "processDisplay": "Washed",
    "image": "/makendi/origins/laos.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Laos Arabica Champasak Typica / Catimor Specialty Grade, Screen 14+ Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 73
  },
  {
    "id": "mk-074-madagascar-elite-grade-east-coast",
    "country": "Madagascar",
    "coffeeType": "Robusta",
    "shortGrade": "Elite Grade (East Coast)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/madagascar.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Madagascar Robusta Elite Grade (East Coast) Elite grade: (Prime category) | ≤30 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Elite grade: (Prime category) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 74
  },
  {
    "id": "mk-075-malawi-misuku-hills-pamwamba",
    "country": "Malawi",
    "coffeeType": "Arabica",
    "shortGrade": "Misuku Hills Pamwamba",
    "processDisplay": "Washed",
    "image": "/makendi/origins/malawi.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Malawi Arabica Misuku Hills Pamwamba Specialty Grade, Screen 15+ | ≤8 defects/300g Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 75
  },
  {
    "id": "mk-076-mexico-finca-puebla-estate-direct-nkg-corporate-farm",
    "country": "Mexico",
    "coffeeType": "Arabica",
    "shortGrade": "Finca Puebla Estate (Direct NKG Corporate Farm)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/mexico.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Mexico Arabica Finca Puebla Estate (Direct NKG Corporate Farm) NMX: Estrictamente Altura, 75% >Screen 15 | ≤13 defects Washed Citrus, Floral, Cocoa NMX: Estrictamente Altura Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 76
  },
  {
    "id": "mk-077-mexico-shg-chiapas-oaxaca-altura",
    "country": "Mexico",
    "coffeeType": "Arabica",
    "shortGrade": "SHG Chiapas / Oaxaca Altura",
    "processDisplay": "Washed",
    "image": "/makendi/origins/mexico.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Mexico Arabica SHG Chiapas / Oaxaca Altura NMX: Estrictamente Altura, Screen 15+ | ≤13 defects Washed Citrus, Floral, Cocoa NMX: Estrictamente Altura Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 77
  },
  {
    "id": "mk-078-mexico-coatepec-washed",
    "country": "Mexico",
    "coffeeType": "Arabica",
    "shortGrade": "Coatepec Washed",
    "processDisplay": "Washed",
    "image": "/makendi/origins/mexico.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Mexico Arabica Coatepec Washed NMX: Prima Lavado, 75% >Screen 14 | ≤21 defects Washed Citrus, Floral, Cocoa NMX: Prima Lavado Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 78
  },
  {
    "id": "mk-079-mexico-veracruz-commercial-premium",
    "country": "Mexico",
    "coffeeType": "Robusta",
    "shortGrade": "Veracruz Commercial Premium",
    "processDisplay": "Natural",
    "image": "/makendi/origins/mexico.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Mexico Robusta Veracruz Commercial Premium Commercial grade | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Commercial grade Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 79
  },
  {
    "id": "mk-080-nicaragua-certified-quality-shg-regional-selects",
    "country": "Nicaragua",
    "coffeeType": "Arabica",
    "shortGrade": "Certified Quality SHG Regional Selects",
    "processDisplay": "Washed",
    "image": "/makendi/origins/nicaragua.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Nicaragua Arabica Certified Quality SHG Regional Selects SHG (>1200m), Screen 15+ | ≤13 defects Washed Citrus, Floral, Cocoa SHG (>1200m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 80
  },
  {
    "id": "mk-081-nicaragua-shg-ep-jinotega-matagalpa",
    "country": "Nicaragua",
    "coffeeType": "Arabica",
    "shortGrade": "SHG EP Jinotega / Matagalpa",
    "processDisplay": "Washed",
    "image": "/makendi/origins/nicaragua.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Nicaragua Arabica SHG EP Jinotega / Matagalpa SHG (>1200m), European Prep, Screen 15+ Washed Citrus, Floral, Cocoa SHG (>1200m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 81
  },
  {
    "id": "mk-082-nicaragua-maragogype-screen-19-elephant-bean",
    "country": "Nicaragua",
    "coffeeType": "Arabica",
    "shortGrade": "Maragogype Screen 19+ (Elephant Bean)",
    "processDisplay": "Washed / Honey",
    "image": "/makendi/origins/nicaragua.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Nicaragua Arabica Maragogype Screen 19+ (Elephant Bean) Screen 19+ (7.50mm+), Maragogype varietal | ≤5 defects Washed / Honey Tropical Fruit, Red Fruit, Caramel Screen 19+ (7.50mm+) Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 82
  },
  {
    "id": "mk-083-panama-geisha-specialty-grade-boquete-valley",
    "country": "Panama",
    "coffeeType": "Arabica",
    "shortGrade": "Geisha Specialty Grade - (Boquete Valley)",
    "processDisplay": "Washed / Natural / Anaerobic",
    "image": "/makendi/origins/panama.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Panama Arabica Geisha Specialty Grade - (Boquete Valley) Specialty G1, Boquete D.O. | ≤5 defects/300g Washed / Natural / Anaerobic Tropical Fruit, Red Fruit, Caramel Specialty G1 Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 83
  },
  {
    "id": "mk-084-panama-shb-boquete-caturra-catuai",
    "country": "Panama",
    "coffeeType": "Arabica",
    "shortGrade": "SHB Boquete Caturra/Catuaí",
    "processDisplay": "Washed",
    "image": "/makendi/origins/panama.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Panama Arabica SHB Boquete Caturra/Catuaí SHB (>1200m), Screen 15+ | ≤8 defects/300g Washed Citrus, Floral, Cocoa SHB (>1200m) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 84
  },
  {
    "id": "mk-085-papua-n-g-aa-grade-screen-18-7mm-premium",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "AA Grade (Screen 18+ / 7mm Premium)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica AA Grade (Screen 18+ / 7mm Premium) Screen 18+ (7.14mm+), Premium Grade Washed Citrus, Floral, Cocoa Screen 18+ (7.14mm+) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 85
  },
  {
    "id": "mk-086-papua-n-g-a-grade-screen-17-6-75mm-formerly-plt",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "A Grade (Screen 17+ / 6.75mm, formerly PLT)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica A Grade (Screen 17+ / 6.75mm, formerly PLT) Screen 17+ (6.70mm) | ≤13 defects Washed Citrus, Floral, Cocoa Screen 17+ (6.70mm) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 86
  },
  {
    "id": "mk-087-papua-n-g-b-grade-standard-smallholder-formerly-psc",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "B Grade - (Standard Smallholder, formerly PSC)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica B Grade - (Standard Smallholder, formerly PSC) Screen 14-16, commercial grade Washed Citrus, Floral, Cocoa Screen 14-16 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 87
  },
  {
    "id": "mk-088-papua-n-g-highlands-and-morobe-smallholder-regional-lots",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "Highlands & Morobe Smallholder Regional Lots",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica Highlands & Morobe Smallholder Regional Lots Regional blend, Screen 14+ | ≤23 defects Washed Citrus, Floral, Cocoa Regional blend Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 88
  },
  {
    "id": "mk-089-papua-n-g-psc-premium-smallholder-coffee-x-a",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "PSC (Premium Smallholder Coffee) X/A",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica PSC (Premium Smallholder Coffee) X/A Premium smallholder, Screen 16+ | ≤13 defects Washed Citrus, Floral, Cocoa Premium smallholder Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 89
  },
  {
    "id": "mk-090-papua-n-g-plantation-a-estate-quality",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "Plantation A - (Estate Quality)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica Plantation A - (Estate Quality) Estate grade, Screen 16+ | ≤13 defects/300g Washed Citrus, Floral, Cocoa Estate grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 90
  },
  {
    "id": "mk-091-papua-n-g-kimel-estate-sigri-plantation-ax",
    "country": "Papua N.G.",
    "coffeeType": "Arabica",
    "shortGrade": "Kimel Estate / Sigri Plantation AX",
    "processDisplay": "Washed",
    "image": "/makendi/origins/papua-n-g.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Papua N.G. Arabica Kimel Estate / Sigri Plantation AX Estate AX grade, Screen 16+ | ≤8 defects Washed Citrus, Floral, Cocoa Estate AX grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 91
  },
  {
    "id": "mk-092-peru-certified-grade-1-traceable-smallholder-cooperatives",
    "country": "Peru",
    "coffeeType": "Arabica",
    "shortGrade": "Certified Grade 1 (Traceable Smallholder Cooperatives)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/peru.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Peru Arabica Certified Grade 1 (Traceable Smallholder Cooperatives) Specialty G1, Screen 15+ | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty G1 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 92
  },
  {
    "id": "mk-093-philippines-mindanao-commercial-g1",
    "country": "Philippines",
    "coffeeType": "Robusta",
    "shortGrade": "Mindanao Commercial G1",
    "processDisplay": "Natural",
    "image": "/makendi/origins/philippines.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Philippines Robusta Mindanao Commercial G1 G1: Screen 16+ | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice G1: Screen 16+ Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 93
  },
  {
    "id": "mk-094-philippines-barako-batangas-standard-grade",
    "country": "Philippines",
    "coffeeType": "Liberica",
    "shortGrade": "Barako - (Batangas Standard Grade)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/philippines.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Philippines Liberica Barako - (Batangas Standard Grade) Liberica varietal, Standard Grade, Screen 14+ Natural / Unwashed Red Fruit, Chocolate, Roasted Nuts Liberica varietal Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 94
  },
  {
    "id": "mk-095-rwanda-fully-washed-supreme-fw-bourbon",
    "country": "Rwanda",
    "coffeeType": "Arabica",
    "shortGrade": "Fully Washed Supreme - (FW, Bourbon)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/rwanda.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Rwanda Arabica Fully Washed Supreme - (FW, Bourbon) Specialty Grade, Bourbon varietal | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 95
  },
  {
    "id": "mk-096-tanzania-kilimanjaro-mbeya-aa",
    "country": "Tanzania",
    "coffeeType": "Arabica",
    "shortGrade": "Kilimanjaro/Mbeya AA",
    "processDisplay": "Washed",
    "image": "/makendi/origins/tanzania.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Tanzania Arabica Kilimanjaro/Mbeya AA Screen 17/18 (7.14mm+), AA grade, density 700+ g/L Washed Citrus, Floral, Cocoa Screen 17/18 (7.14mm+) Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 96
  },
  {
    "id": "mk-097-tanzania-peaberry-tanzanian-pb-specialty",
    "country": "Tanzania",
    "coffeeType": "Arabica",
    "shortGrade": "Peaberry (Tanzanian PB Specialty)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/tanzania.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Tanzania Arabica Peaberry (Tanzanian PB Specialty) PB grade (single round bean, ~5% of crop), Screen 12+ Washed Citrus, Floral, Cocoa PB grade (single round bean Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 97
  },
  {
    "id": "mk-098-tanzania-bukoba-faq-screen-14",
    "country": "Tanzania",
    "coffeeType": "Robusta",
    "shortGrade": "Bukoba FAQ (Screen 14+)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/tanzania.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Tanzania Robusta Bukoba FAQ (Screen 14+) FAQ (Fair Average Quality), Screen 14+ | ≤150 defects Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice FAQ (Fair Average Quality) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 98
  },
  {
    "id": "mk-099-thailand-chiang-mai-doi-chang-specialty",
    "country": "Thailand",
    "coffeeType": "Arabica",
    "shortGrade": "Chiang Mai / Doi Chang Specialty",
    "processDisplay": "Washed / Honey",
    "image": "/makendi/origins/thailand.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Thailand Arabica Chiang Mai / Doi Chang Specialty Specialty Grade, Screen 15+ | ≤8 defects/300g Washed / Honey Tropical Fruit, Red Fruit, Caramel Specialty Grade Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 99
  },
  {
    "id": "mk-100-thailand-chumphon-commercial-grade",
    "country": "Thailand",
    "coffeeType": "Robusta",
    "shortGrade": "Chumphon Commercial Grade",
    "processDisplay": "Natural",
    "image": "/makendi/origins/thailand.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Thailand Robusta Chumphon Commercial Grade Commercial grade, Screen 14+ | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Commercial grade Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 100
  },
  {
    "id": "mk-101-timor-leste-ermera-manufahi-liquica-regional-lots",
    "country": "Timor-Leste",
    "coffeeType": "Híbrido de Timor",
    "shortGrade": "Ermera / Manufahi / Liquiçá Regional Lots",
    "processDisplay": "Washed",
    "image": "/makendi/origins/timor-leste.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Timor-Leste Híbrido de Timor Ermera / Manufahi / Liquiçá Regional Lots Hybrid: Arabica-Robusta cross, Screen 14+ Washed Citrus, Floral, Cocoa Hybrid: Arabica-Robusta cross Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 101
  },
  {
    "id": "mk-102-timor-leste-ermera-organic-g1",
    "country": "Timor-Leste",
    "coffeeType": "Arabica",
    "shortGrade": "Ermera Organic G1",
    "processDisplay": "Washed",
    "image": "/makendi/origins/timor-leste.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Timor-Leste Arabica Ermera Organic G1 Specialty G1, Organic certified | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty G1 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 102
  },
  {
    "id": "mk-103-togo-commercial-grade-barista",
    "country": "Togo",
    "coffeeType": "Robusta",
    "shortGrade": "Commercial Grade Barista",
    "processDisplay": "Natural",
    "image": "/makendi/origins/togo.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Togo Robusta Commercial Grade Barista Commercial grade | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Commercial grade Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 103
  },
  {
    "id": "mk-104-uganda-kaweri-coffee-plantation-estate-direct-nkg-farm",
    "country": "Uganda",
    "coffeeType": "Robusta",
    "shortGrade": "Kaweri Coffee Plantation Estate (Direct NKG Farm)",
    "processDisplay": "Washed / Natural",
    "image": "/makendi/origins/uganda.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Uganda Robusta Kaweri Coffee Plantation Estate (Direct NKG Farm) Estate Robusta, Screen 18+ | ≤150 defects Washed / Natural Dark Cocoa, Roasted Nuts, Spice Estate Robusta Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 104
  },
  {
    "id": "mk-105-uganda-natural-screen-18-premium-bold-line",
    "country": "Uganda",
    "coffeeType": "Robusta",
    "shortGrade": "Natural Screen 18 (Premium bold line)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/uganda.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Uganda Robusta Natural Screen 18 (Premium bold line) Screen 18 (7.14mm+) | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Screen 18 (7.14mm+) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 105
  },
  {
    "id": "mk-106-uganda-natural-screen-15",
    "country": "Uganda",
    "coffeeType": "Robusta",
    "shortGrade": "Natural Screen 15",
    "processDisplay": "Natural",
    "image": "/makendi/origins/uganda.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Uganda Robusta Natural Screen 15 Screen 15 (6.00mm), commercial grade | ≤150 defects/300g Natural / Unwashed Dark Cocoa, Roasted Nuts, Spice Screen 15 (6.00mm) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 106
  },
  {
    "id": "mk-107-uganda-wugar-washed-uganda-arabica-mt-elgon",
    "country": "Uganda",
    "coffeeType": "Arabica",
    "shortGrade": "Wugar - (Washed Uganda Arabica, Mt. Elgon)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/uganda.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Uganda Arabica Wugar - (Washed Uganda Arabica, Mt. Elgon) Specialty Grade, Screen 15+ | ≤8 defects Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 107
  },
  {
    "id": "mk-108-uganda-drugar-dried-uganda-arabica-rwenzori",
    "country": "Uganda",
    "coffeeType": "Arabica",
    "shortGrade": "Drugar - (Dried Uganda Arabica, Rwenzori)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/uganda.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Uganda Arabica Drugar - (Dried Uganda Arabica, Rwenzori) Specialty Grade, Screen 14+, natural dried Unwashed / Dry Processed Red Fruit, Chocolate, Roasted Nuts Specialty Grade Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 108
  },
  {
    "id": "mk-109-vietnam-grade-1-screen-18-clean-color-magnetically-sorted",
    "country": "Vietnam",
    "coffeeType": "Robusta",
    "shortGrade": "Grade 1 Screen 18+ Clean (Color/Magnetically Sorted)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/vietnam.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Vietnam Robusta Grade 1 Screen 18+ Clean (Color/Magnetically Sorted) SNI Q1: Screen 18+ (7.14mm+) | ≤25 defects/300g Natural / Dry Processed Dark Cocoa, Roasted Nuts, Spice SNI Q1: Screen 18+ (7.14mm+) Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 109
  },
  {
    "id": "mk-110-vietnam-catimor-highland-specialty-yeast-and-anaerobic-lots",
    "country": "Vietnam",
    "coffeeType": "Arabica",
    "shortGrade": "Catimor (Highland Specialty Yeast & Anaerobic Lots)",
    "processDisplay": "Experimental / Washed",
    "image": "/makendi/origins/vietnam.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Vietnam Arabica Catimor (Highland Specialty Yeast & Anaerobic Lots) Specialty G1, Screen 15+ | ≤5 defects/300g Experimental / Washed Tropical Fruit, Red Fruit, Caramel Specialty G1 Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 110
  },
  {
    "id": "mk-111-vietnam-grade-1-clean-screen-16-18",
    "country": "Vietnam",
    "coffeeType": "Robusta",
    "shortGrade": "Grade 1 - (Clean, Screen 16/18)",
    "processDisplay": "Wet Polished",
    "image": "/makendi/origins/vietnam.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Vietnam Robusta Grade 1 - (Clean, Screen 16/18) SNI Q1: Screen 16-18 | ≤25 defects/300g Wet Polished Dark Cocoa, Roasted Nuts, Spice SNI Q1: Screen 16-18 Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 111
  },
  {
    "id": "mk-112-vietnam-grade-2-5-black-broken-screen-13",
    "country": "Vietnam",
    "coffeeType": "Robusta",
    "shortGrade": "Grade 2 - (5% Black/Broken, Screen 13)",
    "processDisplay": "Natural",
    "image": "/makendi/origins/vietnam.jpg",
    "tastingNotes": [
      "Dark Cocoa",
      "Roasted Nuts",
      "Spice",
      "Dark Chocolate"
    ],
    "searchText": "Vietnam Robusta Grade 2 - (5% Black/Broken, Screen 13) SNI Q2: 12-25 defects/300g, Screen 13-14 Unwashed / Natural Dark Cocoa, Roasted Nuts, Spice SNI Q2: 12-25 defects/300g Dark Cocoa Roasted Nuts Spice Dark Chocolate Espresso Blends Milk Drinks Cold Brew",
    "sourceNumber": 112
  },
  {
    "id": "mk-113-vietnam-da-lat-high-quality-catimor-lam-dong",
    "country": "Vietnam",
    "coffeeType": "Arabica",
    "shortGrade": "Da Lat High Quality - (Catimor, Lam Dong)",
    "processDisplay": "Washed",
    "image": "/makendi/origins/vietnam.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Vietnam Arabica Da Lat High Quality - (Catimor, Lam Dong) Specialty Grade, Screen 15+ | ≤8 defects Washed Citrus, Floral, Cocoa Specialty Grade Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 113
  },
  {
    "id": "mk-114-vietnam-son-la-specialty-highland-catimor",
    "country": "Vietnam",
    "coffeeType": "Arabica",
    "shortGrade": "Son La Specialty - (Highland Catimor)",
    "processDisplay": "Washed / Honey",
    "image": "/makendi/origins/vietnam.jpg",
    "tastingNotes": [
      "Tropical Fruit",
      "Red Fruit",
      "Caramel",
      "Fermented Fruit"
    ],
    "searchText": "Vietnam Arabica Son La Specialty - (Highland Catimor) Specialty Grade, Screen 15+ | ≤5 defects/300g Washed / Honey Tropical Fruit, Red Fruit, Caramel Specialty Grade Tropical Fruit Red Fruit Caramel Fermented Fruit Filter Coffee Espresso Pour Over Signature Blends",
    "sourceNumber": 114
  },
  {
    "id": "mk-115-yemen-mocha-mattari-sanani-genuine",
    "country": "Yemen",
    "coffeeType": "Arabica",
    "shortGrade": "Mocha Mattari / Sanani Genuine",
    "processDisplay": "Natural",
    "image": "/makendi/origins/yemen.jpg",
    "tastingNotes": [
      "Red Fruit",
      "Chocolate",
      "Roasted Nuts",
      "Caramel"
    ],
    "searchText": "Yemen Arabica Mocha Mattari / Sanani Genuine Heritage Grade, Screen 14-16 | ≤8 defects/300g Dry Processed / Natural Red Fruit, Chocolate, Roasted Nuts Heritage Grade Red Fruit Chocolate Roasted Nuts Caramel Espresso Filter Coffee French Press Blends",
    "sourceNumber": 115
  },
  {
    "id": "mk-116-zambia-aaa-aa-northern-province",
    "country": "Zambia",
    "coffeeType": "Arabica",
    "shortGrade": "AAA/AA Northern Province",
    "processDisplay": "Washed",
    "image": "/makendi/origins/zambia.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Zambia Arabica AAA/AA Northern Province AAA: Screen 19+, AA: Screen 17/18 | ≤8 defects/300g Washed Citrus, Floral, Cocoa AAA: Screen 19+ Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 116
  },
  {
    "id": "mk-117-zimbabwe-calveley-estate-class-1",
    "country": "Zimbabwe",
    "coffeeType": "Arabica",
    "shortGrade": "Calveley Estate Class 1",
    "processDisplay": "Washed",
    "image": "/makendi/origins/zimbabwe.jpg",
    "tastingNotes": [
      "Citrus",
      "Floral",
      "Cocoa",
      "Clean Finish"
    ],
    "searchText": "Zimbabwe Arabica Calveley Estate Class 1 Specialty Class 1, Screen 15+ | ≤5 defects/300g Washed Citrus, Floral, Cocoa Specialty Class 1 Citrus Floral Cocoa Clean Finish Filter Coffee Espresso French Press Blends",
    "sourceNumber": 117
  }
];
