// Generated by scripts/import-origin-catalog.mjs.
// Canonical public set: MAKENDI 117 pages 1–6 plus MAKENDI 1.2 pages 1–54.
// Sparse alternate pages and the four-page duplicate PDF are intentionally excluded.

export const originCatalogMeta = {
  "revision": "2026-07-27",
  "sheetCount": 60,
  "countryCount": 22,
  "canonicalSources": [
    {
      "document": "MAKENDI 117.pptx.pdf",
      "pages": "1–6"
    },
    {
      "document": "MAKENDI 1.2.pdf",
      "pages": "1–54"
    }
  ],
  "excludedSources": [
    {
      "document": "MAKENDI 117.pptx.pdf",
      "pages": "7–60",
      "reason": "duplicate or incomplete alternate layouts"
    },
    {
      "document": "MAKENDI 1.pptx.pdf",
      "pages": "1–4",
      "reason": "exact duplicates of MAKENDI 1.2 pages 51–54"
    }
  ]
};

export const originCatalogIndexUrl = "/catalog/data/origin-index-1534eb6756.json";
