// Generated by scripts/import-origin-catalog.mjs.
// Canonical public set: 117 unique sheets selected from the most complete matching exports.
// Alternate and repeated pages are retained only as audited duplicate references.

export const originCatalogMeta = {
  "revision": "2026-07-27-branded-v4",
  "assetRevision": "brand-integrated-v4",
  "exportedPageCount": 117,
  "sheetCount": 117,
  "countryCount": 38,
  "generatedLanguageCount": 2,
  "generatedDocumentCount": 234,
  "previewPpi": 270,
  "sourceOriginalCount": 117,
  "documentGenerator": "Coffendi branded bilingual origin document generator",
  "decorativeArtwork": "source-visible-context-plus-process-v2",
  "distinctHeroVisualCount": 117,
  "distinctSourceVisualCount": 32,
  "processArtworkFamilies": [
    "honey-mixed",
    "natural",
    "washed"
  ],
  "visualProvenance": "Visibly dominant source-provided context plus non-country-specific process illustration",
  "canonicalSources": [
    {
      "document": "v5 p1.pdf",
      "pages": "1–56"
    },
    {
      "document": "v5 p2.pdf",
      "pages": "1"
    },
    {
      "document": "MAKENDI 117.pptx.pdf",
      "pages": "1–6"
    },
    {
      "document": "MAKENDI 1.2.pdf",
      "pages": "1–54"
    }
  ],
  "excludedSources": [
    {
      "document": "v5 p2.pdf",
      "pages": "2–61",
      "reason": "alternate versions of the selected complete Indonesia–Zimbabwe exports"
    },
    {
      "document": "MAKENDI 117.pptx.pdf",
      "pages": "7–60",
      "reason": "alternate duplicates of MAKENDI 1.2 pages 1–54"
    },
    {
      "document": "MAKENDI 1.pptx.pdf",
      "pages": "1–4",
      "reason": "exact duplicates of MAKENDI 1.2 pages 51–54"
    }
  ]
};

export const originCatalogIndexUrl = "/catalog/data/origin-index-8386fcd12f.json";
